export const APP_LOADED = 'APP_LOADED';

export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const GET_RESTAURANTS_LIST = 'GET_RESTAURANTS_LIST';
export const RESTAURANTS_LIST_UPDATED = 'RESTAURANTS_LIST_UPDATED';