export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CHECK_AUTH_START = 'CHECK_AUTH_START';
export const CHECK_AUTH_END = 'CHECK_AUTH_END';

export const USER_AUTH_UPDATED = 'USER_AUTH_UPDATED';
export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_END = 'USER_LOGIN_END';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT_START = 'USER_LOGOUT_START';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const GET_RESTAURANTS_LIST = 'GET_RESTAURANTS_LIST';
export const RESTAURANTS_LIST_UPDATED = 'RESTAURANTS_LIST_UPDATED';

export const CLEAR_CURRENT_ORDER = 'CLEAR_CURRENT_ORDER';
export const GET_USER_ORDERS = 'GET_USER_ORDERS';
export const UPDATE_CURRENT_ORDER = 'UPDATE_CURRENT_ORDER';
export const UPDATE_PAST_ORDERS = 'UPDATE_PAST_ORDERS';